apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-webapp
  template:
    metadata:
      labels:
        app: ecommerce-webapp
    spec:
      containers:
      - name: ecommerce-container
        image: mohdyusuf7149/ecommerce-webapp:latest
        ports:
        - containerPort: 5000

